version: "3.8"

services:
  app:
    build:
      # current dir i.e recipeAPI
      context: .
      dockerfile: Dockerfile
    ports:
      # map host machine port 8000 to port 8000 on the image
      - "8000:8000"
      # get the changes in realtime from the host to the docker container
      # maps the app directory in the host to the app directory in the docker container
    volumes:
      - ./app:/app
      # commands to run the application in the docker container
      # > sign: allows commands to be written in the next line
      # sh(shell) | -c(run command)
      # python manage.py runserver 0.0.0.0:8000: run django development server
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # environment variables for app service
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=thispostgrespassword
    # app service depends on the db service i.e the db service starts before the app service and db service would be available via the network using the host 'db'
    depends_on:
      - db



  # Database service, adjascent to the app service
  db:
    image: postgres:13-alpine
    # image: postgres
    # volumes:
    #   - ./data/dbdata:/var/lib/postgresql/data

    # environment variables for database service
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thispostgrespassword