# Generated by Django 3.2.6 on 2022-01-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, help_text='Enter username', max_length=255),
            preserve_default=False,
        ),
    ]
