# Generated by Django 3.2.6 on 2022-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'blank': 'Email is a required field, cannot be blank.', 'null': 'Email is a required field cannot be null.', 'unique': 'A user is already registered with this email address'}, help_text='Enter email address', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
